// Generated by CoffeeScript 1.10.0
(function() {
  App.module('Gallery.Albums', function(Albums, App, Backbone, Marionette, $, _) {
    Albums.Controller = {
      showAlbumList: function() {
        var albumCollection, albumCollectionPromise, albumsListView, layout;
        albumCollection = new Albums.Collection;
        albumsListView = new Albums.Views.AlbumCollectionView({
          collection: albumCollection
        });
        albumCollectionPromise = albumCollection.fetch();
        layout = new App.Gallery.Layout;
        layout.render();
        App.getRegion('main').show(layout);
        albumCollectionPromise.done(function() {
          layout.showChildView('content', albumsListView);
        });
      },
      showAlbumDetail: function(id, page) {
        var album, albumDetailLayoutView, albumDetailsItemView, albumPromise, imageCollection, imageCollectionPromise, imagesListView, layout;
        page = page || 1;
        album = new Albums.Model({
          id: id
        });
        imageCollection = new App.Gallery.Images.Collection;
        layout = new App.Gallery.Layout;
        layout.render();
        albumDetailLayoutView = new Albums.Views.AlbumDetailLayoutView;
        albumDetailLayoutView.render();
        albumDetailsItemView = new Albums.Views.AlbumDetailItemView({
          model: album
        });
        imagesListView = new App.Gallery.Images.Views.ImageCollectionView({
          collection: imageCollection
        });
        App.getRegion('main').show(layout);
        layout.showChildView('content', albumDetailLayoutView);
        albumPromise = album.fetch();
        imageCollectionPromise = imageCollection.fetch(null, id, page);
        albumPromise.done(function() {
          albumDetailLayoutView.getRegion('albumDetail').show(albumDetailsItemView);
        });
        imageCollectionPromise.done(function() {
          albumDetailLayoutView.getRegion('albumImages').show(imagesListView);
        });
      }
    };
  });

}).call(this);
