// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  App.module('Gallery.Albums', function(Albums, App, Backbone, Marionette, $, _) {
    Albums.Model = (function(superClass) {
      extend(Model, superClass);

      function Model() {
        return Model.__super__.constructor.apply(this, arguments);
      }

      Model.prototype.url = function() {
        return '/albums/' + this.id;
      };

      Model.prototype.parse = function(response) {
        return response.data;
      };

      return Model;

    })(Backbone.Model);
  });

}).call(this);
