// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  App.module('Gallery.Albums', function(Albums, App, Backbone, Marionette, $, _) {
    Albums.Collection = (function(superClass) {
      extend(Collection, superClass);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.url = '/albums';

      Collection.prototype.parse = function(response) {
        return response.data;
      };

      return Collection;

    })(Backbone.Collection);
  });

}).call(this);
