// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  App.module('Gallery.Images', function(Images, App, Backbone, Marionette, $, _) {
    Images.Views = {};
    Images.Views.ImageItemView = (function(superClass) {
      extend(ImageItemView, superClass);

      function ImageItemView() {
        return ImageItemView.__super__.constructor.apply(this, arguments);
      }

      ImageItemView.prototype.className = 'col-sm-5ths col-xs-6';

      ImageItemView.prototype.template = '#image-item-view-template';

      return ImageItemView;

    })(Marionette.ItemView);
    Images.Views.ImageCollectionView = (function(superClass) {
      extend(ImageCollectionView, superClass);

      function ImageCollectionView() {
        return ImageCollectionView.__super__.constructor.apply(this, arguments);
      }

      ImageCollectionView.prototype.className = 'row';

      ImageCollectionView.prototype.childView = Images.Views.ImageItemView;

      ImageCollectionView.prototype.collectionEvents = {
        'sync': 'render'
      };

      ImageCollectionView.prototype.onBeforeRender = function() {
        if (this.collection.pager && this.collection.pager.pageCount > 1) {
          this.triggerMethod('generate:pager', this.collection.pager);
        }
      };

      return ImageCollectionView;

    })(Marionette.CollectionView);
  });

}).call(this);
