// Generated by CoffeeScript 1.10.0
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  App.module('Gallery.Images', function(Images, App, Backbone, Marionette, $, _) {
    Images.Collection = (function(superClass) {
      extend(Collection, superClass);

      function Collection() {
        return Collection.__super__.constructor.apply(this, arguments);
      }

      Collection.prototype.fetch = function(options, album_id, page) {
        options = options || {};
        options.url = '/albums/' + album_id + '/images';
        if (page) {
          options.url += '?page=' + page;
        }
        return Backbone.Collection.prototype.fetch.call(this, options);
      };

      Collection.prototype.parse = function(response) {
        this.pager = response.pager;
        return response.data;
      };

      return Collection;

    })(Backbone.Collection);
  });

}).call(this);
